name: Deploy to Firebase and Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/**'
  workflow_dispatch: {} # manual runs allowed

jobs:
  # Detect which parts changed
  filter:
    name: Detect changed paths
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: filter
        name: Filter changed paths
        uses: dorny/paths-filter@v2
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'

  # Deploy backend (only if backend changed)
  deploy-backend:
    name: Deploy Backend to Cloud Run
    needs: filter
    runs-on: ubuntu-latest
    if: ${{ needs.filter.outputs.backend == 'true' }}
    env:
      PROJECT_ID: kai-developer-test
      IMAGE: gcr.io/kai-developer-test/kai-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Authenticate to Google Cloud (using service account JSON in secret)
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Build and push Docker image to Container Registry
        run: |
          cd backend
          # Build and push image to GCR
          gcloud builds submit --tag $IMAGE

      - name: Deploy to Cloud Run (container listens on port 8000)
        run: |
          gcloud run deploy kai-backend \
            --image $IMAGE \
            --platform managed \
            --region us-central1 \
            --port=8000 \
            --allow-unauthenticated \
            --set-env-vars FIRESTORE_DATABASE_ID=${{ secrets.FIRESTORE_DATABASE_ID }},PROJECT_ID=${{ env.PROJECT_ID }} \
            --set-secrets=OPENAI_API_KEY=openai-api-key:latest \
            --service-account=firebase-adminsdk-fbsvc@kai-developer-test.iam.gserviceaccount.com \
            --max-instances=10 \
            --memory=512Mi \
            --timeout=300

  # Deploy frontend (only if frontend changed)
  deploy-frontend:
    name: Deploy Frontend to Firebase Hosting
    needs: filter
    runs-on: ubuntu-latest
    if: ${{ needs.filter.outputs.frontend == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Build Next.js app
        run: |
          cd frontend
          npm run build
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: kai-developer-test.firebaseapp.com
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: kai-developer-test
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: kai-developer-test.firebasestorage.app
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: 320177389465
          NEXT_PUBLIC_FIREBASE_APP_ID: 1:320177389465:web:23619186ec45c714b7dd08
          NEXT_PUBLIC_API_URL: https://kai-backend-eh4pzlsddq-uc.a.run.app

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          channelId: live
          projectId: kai-developer-test
          entrypoint: ./frontend
